# Generated by Django 4.2.3 on 2023-07-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_weather_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
